
WARNING = "warning"
SUCCESS = "success"
ERROR = "error"

PUBLISH = "PUBLISH"
SUBSCRIBE = "SUBSCRIBE"
UNSUBSCRIBE = "UNSUBSCRIBE"
SET = "SET"
GET = "GET"
PUSH = "PUSH"
POP = "POP"
RANGE = "RANGE"

commands = {"PUBLISH","SUBSCRIBE","UNSUBSCRIBE","SET","GET","PUSH","POP","RANGE"}